### PR TITLE
turned testing back on in GitHub actions cmake workflow

### LINKED ISSUE #58: add CI testing with GitHub actions
We are currently in the process of adding CI testing with GitHub actions.

Currently, make test is failing.

### PR DESCRIPTION
**Pull request by captainkirk99**
Turn on testing in GitHub actions. 

Fixes #58

### CODE REVIEW

**Comment by captainkirk99** [comment]
@michaelleerilee this is how the test is failing in GitHub actions:

```
 make VERBOSE=1 test
Running tests...
/usr/local/bin/ctest --force-new-ctest-process 
Test project /home/runner/work/STARE/STARE/build

    Start 1: STARETests
Errors while running CTest
1/1 Test #1: STARETests .......................***Exception: SegFault  0.97 sec
make: *** [test] Error 8
0% tests passed, 1 tests failed out of 1
Total Test time (real) =   1.03 sec
The following tests FAILED:
	  1 - STARETests (SEGFAULT)
```

**Comment by michaelleerilee** [comment]
An environment variable telling the test where to find data needs to be set. It currently segfaults instead of something more appropriate.


Sent from Smallbiz Yahoo Mail for iPhone


On Saturday, September 12, 2020, 09:14, Captain James Tiberius Kirk <notifications@github.com> wrote:




@michaelleerilee this is how the test is failing in GitHub actions:
 make VERBOSE=1 test
Running tests...
/usr/local/bin/ctest --force-new-ctest-process 
Test project /home/runner/work/STARE/STARE/build

    Start 1: STARETests
Errors while running CTest
1/1 Test #1: STARETests .......................***Exception: SegFault  0.97 sec
make: *** [test] Error 8
0% tests passed, 1 tests failed out of 1
Total Test time (real) =   1.03 sec
The following tests FAILED:
	  1 - STARETests (SEGFAULT)

**Comment by captainkirk99** [comment]
OK, if I understand you correctly, the test requires a data file that is not part of the repo?

Is it a very big data file? Can it be added to the repo? THat would be the easiest solution...

**Comment by michaelleerilee** [comment]
It is part of the repo, but out-of-source builds with cmake need to find the test data. I did it with an environment variable. There's probably a way to tell cmake where to find that data or set the environment variable. I thought I did that, but it sounds like what I did doesn't work.
It looks like STARE/tests/CUTE/polygons is copied (cf. STARE/tests/CUTE/CMakeLists.txt), but it seems that the test code isn't finding it. 
https://github.com/SpatioTemporal/STARE/blob/master/tests/CUTE/STARE_Covers_test.cpp
 
The above looks for the environment variable STARE_SRC_HOME, and if it can't find the env. variable, it assumes the test is being run from the top level of the source distribution. I'm guessing the test is either being run from the top level of the build directory or from the test directory within the build directory.    On Sunday, September 13, 2020, 01:05:32 PM EDT, Captain James Tiberius Kirk <notifications@github.com> wrote:  
 
 


OK, if I understand you correctly, the test requires a data file that is not part of the repo?

Is it a very big data file? Can it be added to the repo? THat would be the easiest solution...

**Comment by michaelleerilee** [comment]
Fixed via: https://github.com/SpatioTemporal/STARE/pull/61

**Pull request closed without merging**
